"""Validate src/baselines/benjaafar_2013.py against Theorem A.1.

The Benjaafar (2013) paper does not publish a Hua-style table of numerical
solutions; its main results are 15 figures generated by a multi-period
MILP whose per-figure parameters are not all printed in the paper.

Its analytical companion (Appendix II-B, Theorem A.1) gives the closed
form for the EOQ-style problem under a strict carbon cap. Our validation
strategy is therefore:

    (1) Reproduce Theorem A.1 itself across all three regimes
        (cap not binding, cap binding, infeasible) using parameter
        sets where the analytical Q*, c_hat, c_min are computable
        directly from the formulas.
    (2) Cross-check the carbon-tax solver against Hua 2011's
        cap-and-trade closed form (the two coincide up to the rebate
        term -alpha * cap that tax does not include).
    (3) Cross-check the cap-and-offset solver against the strict-cap
        and tax solvers in the limiting regimes the paper identifies
        (Observation 4 / Section II-B).
    (4) Sanity: classical-EOQ recovery as alpha -> 0 / cap -> infinity.
"""

from __future__ import annotations

import math

import pytest

from src.baselines.benjaafar_2013 import (
    solve_benjaafar_2013_offset,
    solve_benjaafar_2013_strict_cap,
    solve_benjaafar_2013_tax,
)
from src.baselines.hua_2011 import solve_hua_2011_cap_and_trade


# ---------------------------------------------------------------------------
# Reusable parameter set: Hua row 3 with K/h > e/h_e, so Q_0 > Q_e.
#   Q_0 = sqrt(2*200*60000/0.36)         = 8164.965809...
#   Q_e = sqrt(2*450*60000/1)            = 7348.469228...
#   c_hat = 450*60000/Q_0 + 1*Q_0/2      = 7389.314684...
#   c_min = sqrt(2*450*1*60000)          = 7348.469228...
# ---------------------------------------------------------------------------
HUA_R3 = dict(K=200, d=60000, h=0.36, e=450, h_e=1.0)
EXPECT_Q0 = math.sqrt(2 * 200 * 60000 / 0.36)
EXPECT_QE = math.sqrt(2 * 450 * 60000 / 1.0)
EXPECT_CHAT = 450 * 60000 / EXPECT_Q0 + EXPECT_Q0 / 2.0
EXPECT_CMIN = math.sqrt(2 * 450 * 1.0 * 60000)


def _strict_cap_quadratic(*, e, h_e, d, cap, nu=0.0) -> tuple[float, float]:
    """Roots of h_e Q^2 - 2(cap - nu d) Q + 2 e d = 0 (Theorem A.1 boundary)."""
    bb = cap - nu * d
    disc = bb * bb - 2.0 * e * h_e * d
    if disc < 0:
        raise ValueError("cap below c_min")
    s = math.sqrt(disc)
    return (bb - s) / h_e, (bb + s) / h_e


# ---------------------------------------------------------------------------
# (1) Strict cap — Theorem A.1
# ---------------------------------------------------------------------------

def test_strict_cap_anchors_match() -> None:
    """The result dict reports Q_classical, Q_minemit, c_hat, c_min correctly."""
    out = solve_benjaafar_2013_strict_cap(**HUA_R3, cap=EXPECT_CHAT * 2)
    assert math.isclose(out["Q_classical"], EXPECT_Q0, rel_tol=1e-12)
    assert math.isclose(out["Q_minemit"], EXPECT_QE, rel_tol=1e-12)
    assert math.isclose(out["cap_at_classical"], EXPECT_CHAT, rel_tol=1e-12)
    assert math.isclose(out["cap_minimum"], EXPECT_CMIN, rel_tol=1e-12)


def test_strict_cap_not_binding() -> None:
    """cap >= c_hat: Q* = Q_0, classical EOQ optimum, no constraint binding."""
    out = solve_benjaafar_2013_strict_cap(**HUA_R3, cap=10000.0)
    assert math.isclose(out["Q_star"], EXPECT_Q0, rel_tol=1e-12)
    assert out["binding"] is False
    assert out["emissions"] < 10000.0


def test_strict_cap_binding_q0_above_qe() -> None:
    """K/h > e/h_e (Q_0 > Q_e): cap binds at the larger root Q2."""
    cap = 7370.0
    Q1, Q2 = _strict_cap_quadratic(e=450, h_e=1.0, d=60000, cap=cap)
    out = solve_benjaafar_2013_strict_cap(**HUA_R3, cap=cap)
    assert math.isclose(out["Q_star"], Q2, rel_tol=1e-12)
    assert out["binding"] is True
    assert math.isclose(out["emissions"], cap, abs_tol=1e-9)


def test_strict_cap_binding_q0_below_qe() -> None:
    """K/h < e/h_e (Q_0 < Q_e): cap binds at the smaller root Q1."""
    params = dict(K=200, d=60000, h=1.0, e=450, h_e=0.36)
    Q0_swapped = math.sqrt(2 * 200 * 60000 / 1.0)
    Qe_swapped = math.sqrt(2 * 450 * 60000 / 0.36)
    assert Q0_swapped < Qe_swapped
    cap = 5000.0
    Q1, _Q2 = _strict_cap_quadratic(e=450, h_e=0.36, d=60000, cap=cap)
    out = solve_benjaafar_2013_strict_cap(**params, cap=cap)
    assert math.isclose(out["Q_star"], Q1, rel_tol=1e-12)
    assert out["binding"] is True
    assert math.isclose(out["emissions"], cap, abs_tol=1e-9)


def test_strict_cap_infeasible() -> None:
    """cap < c_min: ValueError."""
    with pytest.raises(ValueError, match="below minimum"):
        solve_benjaafar_2013_strict_cap(**HUA_R3, cap=7000.0)


def test_strict_cap_at_qe_when_cap_equals_cmin() -> None:
    """cap == c_min: feasible region collapses to {Q_e}."""
    out = solve_benjaafar_2013_strict_cap(**HUA_R3, cap=EXPECT_CMIN)
    assert math.isclose(out["Q_star"], EXPECT_QE, rel_tol=1e-9)
    assert math.isclose(out["emissions"], EXPECT_CMIN, abs_tol=1e-6)


# ---------------------------------------------------------------------------
# (2) Tax — equivalence with Hua's cap-and-trade Q* (rebate aside)
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("alpha", [0.05, 0.2, 0.5, 1.0, 2.0])
def test_tax_q_star_matches_hua_cap_and_trade(alpha: float) -> None:
    """Q* under tax(alpha) coincides with Hua cap-and-trade(C=alpha)."""
    benj = solve_benjaafar_2013_tax(**HUA_R3, alpha=alpha)
    hua = solve_hua_2011_cap_and_trade(
        K=200, D=60000, h=0.36, e=450, g=1.0, C=alpha, a=0.0,
    )
    assert math.isclose(benj["Q_star"], hua["Q_star"], rel_tol=1e-12)


@pytest.mark.parametrize("alpha", [0.05, 0.2, 0.5, 1.0, 2.0])
def test_tax_cost_equals_hua_cost_when_a_zero(alpha: float) -> None:
    """At a=0, Hua's TC(Q*) = sqrt(2 (K+Ce)(h+Cg) D) = Benjaafar tax cost."""
    benj = solve_benjaafar_2013_tax(**HUA_R3, alpha=alpha)
    hua = solve_hua_2011_cap_and_trade(
        K=200, D=60000, h=0.36, e=450, g=1.0, C=alpha, a=0.0,
    )
    assert math.isclose(benj["cost"], hua["cost"], rel_tol=1e-12)


def test_tax_zero_alpha_recovers_classical_eoq() -> None:
    out = solve_benjaafar_2013_tax(**HUA_R3, alpha=0.0)
    assert math.isclose(out["Q_star"], EXPECT_Q0, rel_tol=1e-12)
    assert out["binding"] is False
    classical_cost = 200 * 60000 / EXPECT_Q0 + 0.36 * EXPECT_Q0 / 2.0
    assert math.isclose(out["cost"], classical_cost, rel_tol=1e-12)


# ---------------------------------------------------------------------------
# (3) Cap-and-offset — three regimes
# ---------------------------------------------------------------------------

def test_offset_cap_not_binding() -> None:
    """If c_hat <= cap, no offset purchased; classical EOQ optimum."""
    out = solve_benjaafar_2013_offset(**HUA_R3, cap=10000.0, alpha=1.0)
    assert math.isclose(out["Q_star"], EXPECT_Q0, rel_tol=1e-12)
    assert out["offset"] == 0.0
    assert out["binding"] is False


def test_offset_purchased_when_alpha_small() -> None:
    """With small alpha, Q_alpha stays close to Q_0; emissions exceed cap;
    firm purchases offsets z = f(Q_alpha) - cap."""
    cap = 7370.0
    alpha = 0.05
    out = solve_benjaafar_2013_offset(**HUA_R3, cap=cap, alpha=alpha)
    Keff = 200 + alpha * 450
    heff = 0.36 + alpha * 1.0
    Q_alpha_expected = math.sqrt(2 * Keff * 60000 / heff)
    f_expected = 450 * 60000 / Q_alpha_expected + Q_alpha_expected / 2.0
    assert math.isclose(out["Q_star"], Q_alpha_expected, rel_tol=1e-12)
    assert out["offset"] > 0.0
    assert math.isclose(out["offset"], f_expected - cap, rel_tol=1e-9)
    assert out["binding"] is True


def test_offset_falls_back_to_strict_cap_when_alpha_large() -> None:
    """With large alpha, Q_alpha approaches Q_e; if f(Q_alpha) < cap the
    firm prefers the strict-cap boundary to paying offsets."""
    cap = 7370.0
    out_offset = solve_benjaafar_2013_offset(**HUA_R3, cap=cap, alpha=10.0)
    out_strict = solve_benjaafar_2013_strict_cap(**HUA_R3, cap=cap)
    assert math.isclose(out_offset["Q_star"], out_strict["Q_star"], rel_tol=1e-12)
    assert out_offset["offset"] == 0.0


def test_offset_below_cmin_must_purchase() -> None:
    """When cap < c_min the strict-cap problem is infeasible, but with
    cap-and-offset the firm always has the option to buy more permits."""
    cap = 7300.0
    alpha = 0.05
    out = solve_benjaafar_2013_offset(**HUA_R3, cap=cap, alpha=alpha)
    Keff = 200 + alpha * 450
    heff = 0.36 + alpha * 1.0
    Q_alpha_expected = math.sqrt(2 * Keff * 60000 / heff)
    assert math.isclose(out["Q_star"], Q_alpha_expected, rel_tol=1e-12)
    assert out["offset"] > 0.0


# ---------------------------------------------------------------------------
# (4) Cross-policy invariants
# ---------------------------------------------------------------------------

def test_strict_cap_cost_dominates_classical_when_binding() -> None:
    """Theorem A.1 corollary: a binding cap raises cost above the classical EOQ."""
    cap = 7370.0
    out = solve_benjaafar_2013_strict_cap(**HUA_R3, cap=cap)
    classical_cost = 200 * 60000 / EXPECT_Q0 + 0.36 * EXPECT_Q0 / 2.0
    assert out["cost"] > classical_cost - 1e-9


def test_offset_is_never_more_expensive_than_strict_cap() -> None:
    """Cap-and-offset weakly dominates strict cap when both feasible."""
    cap = 7370.0
    out_offset = solve_benjaafar_2013_offset(**HUA_R3, cap=cap, alpha=0.05)
    out_strict = solve_benjaafar_2013_strict_cap(**HUA_R3, cap=cap)
    assert out_offset["cost"] <= out_strict["cost"] + 1e-9


def test_unified_keys_present() -> None:
    """All three solvers return the unified result-dict keys."""
    cap = 10000.0
    for out in (
        solve_benjaafar_2013_strict_cap(**HUA_R3, cap=cap),
        solve_benjaafar_2013_tax(**HUA_R3, alpha=0.5),
        solve_benjaafar_2013_offset(**HUA_R3, cap=cap, alpha=0.5),
    ):
        for key in ("Q_star", "T_star", "cost", "emissions"):
            assert key in out
        assert math.isclose(out["T_star"], out["Q_star"] / 60000, rel_tol=1e-12)


# ---------------------------------------------------------------------------
# (5) Theorem A.1 numerical example: a hand-computable specific case.
# ---------------------------------------------------------------------------

def test_theorem_a1_worked_example() -> None:
    """A specific (K, d, h, e, h_e, cap) where Q* and emissions are computed
    by hand from the formulas in Theorem A.1."""
    params = dict(K=200, d=60000, h=0.36, e=450, h_e=1.0)
    cap = 7370.0
    # h_e Q^2 - 2 cap Q + 2 e d = 0 => Q^2 - 14740 Q + 54e6 = 0
    disc = 14740**2 - 4 * 54_000_000
    expected_Q1 = (14740 - math.sqrt(disc)) / 2
    expected_Q2 = (14740 + math.sqrt(disc)) / 2
    out = solve_benjaafar_2013_strict_cap(**params, cap=cap)
    # Q_0 = 8164.97 > Q_e = 7348.47 => Q* = Q2.
    assert math.isclose(out["Q_star"], expected_Q2, rel_tol=1e-12)
    assert math.isclose(out["emissions"], cap, abs_tol=1e-9)
    expected_cost = 200 * 60000 / expected_Q2 + 0.36 * expected_Q2 / 2.0
    assert math.isclose(out["cost"], expected_cost, rel_tol=1e-12)
    assert expected_Q1 < out["Q_minemit"] < expected_Q2
